name: Mirroring
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  delete:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror to Github
      uses: pixta-dev/repository-mirroring-action@v3
        with:
          target_repo_url:
            git@github.com:EpitechPromo2027/B-DOP-200-NAN-2-1-bschocolatine-thomas.boue.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
