name: what_time_is_it
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  - build:
    - runs-on: ubuntu-latest
    - steps:
      - name: Run the date command
      - run: |
        date

